#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Set application name
application=`getApplication`

# Run
runParallel $application 2

# Reconstruct
runApplication reconstructPar -noFunctionObjects

# if single processor
# runApplication $application
# ----------------------------------------------------------------- end-of-file
