#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Set application name
application=`getApplication`

\rm -rf 0

# Meshing
# # runApplication blockMesh
# runApplication surfaceFeatureExtract
# runApplication snappyHexMesh -overwrite
# runApplication createBaffles -overwrite
# runApplication mergeOrSplitBaffles -split -overwrite

# Get rid of zero faced patches
# runApplication createPatch -overwrite

# Copy fields after meshing to avoind the generation of unnecessary patch fields
\cp -r 0.org 0

# runApplication topoSet
# Initialize alpha
runApplication setFields
# Decompose
runApplication decomposePar -force

# Run
runParallel $application 2

# Reconstruct
runApplication reconstructPar -noFunctionObjects

# if single processor
# runApplication $application
# ----------------------------------------------------------------- end-of-file
